#include <iostream>
#include <string>
#include <fstream>
#include <sstream>
#include <cstring>
#include <unistd.h>
#include <cstdlib>
#include <cstdio>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/wait.h>